[package]
name = "translation-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-sdk = "0.6.2"
tokio = { version = "1", features = ["full"] }
deepl = "0.1.6"
